# Setup

title:            Pages Example
url: https://remalucard.github.io/PagesExample
repository: remalucard/PagesExample

permalink: pretty

# Configuration
plugins: 
- jekyll-remote-theme

# color scheme
color_scheme: catppuccin

remote_theme: just-the-docs/just-the-docs

# search function
search_enabled: true

# back to top
back_to_top: true
back_to_top_text: "Back To Top"

#edit ig?
gh_edit_link: false


#mermaid diagram
mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "9.1.3"
